export const cht = {
  "login": "登入",
  "userNotFound": "使用者不存在！",
  "wrongPassword": "密碼錯誤！",
  "welcomeBack": "歡迎回來",
  "userAccount": "使用者帳號",
  "password": "密碼",
  "forgotPassword": "忘記密碼",
  "call902": "請洽分機902",
  "manualInput": "手動輸入",
  "alert": "提示",
  "procedureExist1": "此流程原本就存在於系統中，重量為",
  "procedureExist2": "，已覆寫為",
  "insertProcedureSuccess": "新增流程成功！",
  "insertProcedure": "新增製程",
  "workno": "派工單號",
  "containerno": "桶號",
  "chooseProcedure": "選擇製程",
  "searchProcedure": "查詢製程",
  "weightKG": "重量（公斤）",
  "insertDatabase": "寫入資料庫",
  "timeToWork": "上工囉！",
  "goToWork": "去工作",
  "logout": "登出",
  "loading": "資料讀取中",
  "userInfo": "個人資料",
  "name": "姓名： ",
  "queryResult": "查詢結果",
  "procedure": "製程",
  "originalWeight": "重量",
  "resultWeight": "回重",
  "queryWorkno": "查詢單號",
  "worknoNotFound": "查無此單號",
  "query": "查詢",
  "home": "首頁",
  "insert": "插入",
  "profile": "個人資料"
};

export const en = {
  "login": "Login",
  "userNotFound": "User Not Found!",
  "wrongPassword": "Wrong Password！",
  "welcomeBack": "Welcome Back",
  "userAccount": "User Account",
  "password": "Password",
  "forgotPassword": "Forgot Password",
  "call902": "Call #902 for assistance",
  "manualInput": "Manual Input",
  "alert": "Prompt",
  "procedureExist1": "Procedure exists! It was ",
  "procedureExist2": ", and is modified to ",
  "insertProcedureSuccess": "Insert Procedure Successful!",
  "insertProcedure": "Insert Procedure",
  "workno": "Work Number",
  "containerno": "Container Number",
  "chooseProcedure": "Choose Procedure",
  "searchProcedure": "Search Procedure",
  "weightKG": "weight(KG)",
  "insertDatabase": "Insert",
  "timeToWork": "Time To Work!",
  "goToWork": "Go To Work",
  "logout": "Logout",
  "loading": "Loading",
  "userInfo": "User Information",
  "name": "Name: ",
  "queryResult": "Query Result",
  "procedure": "Procedure",
  "originalWeight": "Original Weight",
  "resultWeight": "Result Weight",
  "queryWorkno": "Query Work Number",
  "worknoNotFound": "Work Number Not Found",
  "query": "Query",
  "home": "Home",
  "insert": "Insert",
  "profile": "Profile"
};